server:
  port: 8081
  servlet:
    context-path: /server
spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api?serverTimezone=GMT%2B8
    username: ENC(lgpCOb0fh+3clp4Euo9BXA==)
    password: ENC(5Uhur3mwlqJA3+bdxzKrRlIuqUjed/W3)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail: # 邮件配置
    host: smtp.qq.com
    username: ENC(6A63N3lvQmd/NCKURbJ6QvoJLliSx2Q5HCJGvOf0zww=)
    password: ENC(a6703L7xSqI3iMxPA/pcBsTij/N3OqyM4K/H/Ie0130=) # 邮件客户端授权码
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis: # redis配置
    host: localhost # redis服务器地址
    port: 6379 # 端口
    password: ENC(LQLFURaSg//NPEid2EAgI4r3rpqqumkh) # 密码
    database: 2 # 数据库索引
    timeout: 5000 # 连接超时时间
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数(使用负值表示没有限制)
        max-idle: 10 # 连接池中最小空闲连接
        max-wait: 100000 # 连接池最大阻塞等待时间(使用负值表示没有限制)
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名匹配映射
  mapper-locations: classpath:mapper/*.xml # xml映射文件位置
  type-aliases-package: com.test.api.api.bean # 对应实体类的路径
logging:
  level:
    com.test.api.api.dao: debug
  config: classpath:log4j2.xml # 指定log4j配置文件的位置
pagehelper: # 分页配置
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

head:
  portrai:
    path: /Users/wangsheng/headPortrai/

login: # 用户登录过期时间 1h
  time: 3600
# 自定义swagger配置 访问地址 http://localhost:8081/server/swagger-ui/index.html#/
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}


