server:
  port: 8081
  servlet:
    context-path: /server
#spring:
#  application:
#    name: api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api?serverTimezone=GMT%2B8
    username: root
    password: helloser
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail: # 邮件配置
    host: smtp.qq.com
    username: 1689841661@qq.com
    password: nkfpmbygbjpubbeh # 邮件客户端授权码
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml # xml映射文件位置
  type-aliases-package: com.test.api.api.bean # 对应实体类的路径
logging:
  level:
    com.test.api.api.dao: debug
  config: classpath:log4j2.xml # 指定log4j配置文件的位置
pagehelper: # 分页配置
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

head:
  portrai:
    path: /Users/wangsheng/headPortrai/
